<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "peezzer_bmi_rechner"
 *
 * Auto generated by Extension Builder 2013-04-30
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'BMI Calculator',
	'description' => 'BMI Calculator, with simple statistics.',
	'category' => 'PEEZZER',
	'author' => 'Sergiu Popovici',
	'author_email' => 'sergiu.popovici@gmail.com',
	'author_company' => 'PEEZZER',
	'shy' => '',
	'priority' => '',
	'module' => '',
	'state' => 'beta',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'modify_tables' => '',
	'clearCacheOnLoad' => 0,
	'lockType' => '',
	'version' => '1.0.1',
	'constraints' => array(
		'depends' => array(
			'extbase' => '6.0',
			'fluid' => '6.0',
			'typo3' => '6.0',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);

?>